function setPath()
%
% path = setPath()
%
% description:
%     sets all necessary paths
%

includepaths = {
     '/Base/Classes', ...
     '/Base/Parameter',... 
     '/Base/Algorithms',...
     '/Base/Algorithms/Geometry',...     
     '/Base/Algorithms/GraphTheory',...     
     '/Base/Algorithms/SignalProcessing',...  
     '/Base/Utils',...
     '/Base/Utils/ImTools',...
     ...
     '/ImageProcessing/', ...
     '/ImageProcessing/Filtering', ...
     '/ImageProcessing/Photometry', ...
     '/ImageProcessing/Segmentation', ...
     '/ImageProcessing/Stitching', ...
     '/ImageProcessing/Tracking',...
     ...
     '/Interface',...
     '/Interface/ImageFormats',...
     '/Interface/ImageJ',...
     '/Interface/Imaris',...
     '/Interface/MetaMorph',...
     '/Interface/Movies',...
     '/Interface/Python',...
     '/Interface/Ilastik',...
     '/Interface/Tags',...
     '/Interface/Hugin',...
     ...
     '/Test'...
};
 
basepath = fileparts(mfilename('fullpath'));

for p = 1:length(includepaths)
   includepaths{p} = fullfile(basepath, includepaths{p});
end

addpath(includepaths{:});
     
          
% compability to matlab previous versions
v = version('-release');
if length(v) >= 4
   v = v(1:4);
   if strcmp(v, '2012')
      addpath(fullfile(basepath, '/Base/Utils/External/Matlab2012'));
   end
end

      
end

